"""external_id not null

Revision ID: ec685518d041
Revises: 0001_create_vacancies
Create Date: 2026-02-14 14:53:32.649141
"""

from alembic import op
import sqlalchemy as sa


revision = 'ec685518d041'
down_revision = '0001_create_vacancies'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacancies', 'external_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacancies', 'external_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
